// <auto-generated />
namespace Assignment_3rd_run.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IntialSetUp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntialSetUp));
        
        string IMigrationMetadata.Id
        {
            get { return "202110050842086_IntialSetUp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
